# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.rotation_edit = QtWidgets.QLineEdit(self.widget)
        self.rotation_edit.setGeometry(QtCore.QRect(210, 100, 113, 23))
        self.rotation_edit.setObjectName("rotation_edit")
        self.orientation_edit = QtWidgets.QComboBox(self.widget)
        self.orientation_edit.setGeometry(QtCore.QRect(158, 60, 171, 23))
        self.orientation_edit.setObjectName("orientation_edit")
        self.scale_edit = QtWidgets.QLineEdit(self.widget)
        self.scale_edit.setGeometry(QtCore.QRect(210, 140, 113, 23))
        self.scale_edit.setObjectName("scale_edit")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 100, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 60, 121, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.display_phase_imag = GraphicsLayoutWidget(self.centralwidget)
        self.display_phase_imag.setObjectName("display_phase_imag")
        self.horizontalLayout_4.addWidget(self.display_phase_imag)
        self.display_intens_real = GraphicsLayoutWidget(self.centralwidget)
        self.display_intens_real.setObjectName("display_intens_real")
        self.horizontalLayout_4.addWidget(self.display_intens_real)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.view_toggle = QtWidgets.QPushButton(self.centralwidget)
        self.view_toggle.setObjectName("view_toggle")
        self.gridLayout.addWidget(self.view_toggle, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.view_toggle.clicked.connect(MainWindow.TogglePlotRE_IM)
        self.rotation_edit.textChanged['QString'].connect(MainWindow.ProcessingUpdated)
        self.pushButton.clicked.connect(MainWindow.Start_Stop_Clicked)
        self.scale_edit.textChanged['QString'].connect(MainWindow.ProcessingUpdated)
        self.orientation_edit.currentIndexChanged['QString'].connect(MainWindow.ProcessingUpdated)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "rotation (degrees)"))
        self.label_2.setText(_translate("MainWindow", "scale"))
        self.label_3.setText(_translate("MainWindow", "orientation"))
        self.view_toggle.setText(_translate("MainWindow", "Real/Imag"))
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
